[workspace.package]
version = "0.0.1"
edition = "2024"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

[workspace]
members = [
  "crates/*",
]
resolver = "3"
